### PR TITLE
Add Initial Issue Forms

### PR DESCRIPTION
**Pull request by beeequeue**
Adds nice forms for people to fill out when reporting issues

They also automatically add these labels if you create them in the repo:
`ability`, `ability-draft`, `cosmetic`, `item`, and `tooltip`

[Docs about the feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

[See exactly how it looks in my fork](https://github.com/BeeeQueue/Dota2/issues/new/choose)

<details>
<summary>Screenshots</summary>

image

image

</details>

### CODE REVIEW

**Comment by BeeeQueue** [comment]
@jeffhill

**Comment by Cryszon** [comment]
Should probably add a non-mandatory Match ID field to "Other" issue type as well. From what I understand they are very helpful in debugging issues and should be included whenever possible.

**Comment by jeffhill** [comment]
Thank you, this looks great!

**Comment by Ahimtar** [comment]
There are multiple typos over the place - two "l"s in Abillity Draft and Abillity Bug, in the description of Cosmetic bugs there's "costmetic".

I'd recommend putting "Other" as the last category in the list too (and possibly sort the remains alphabetically).

**Comment by peauc** [comment]
@Ahimtar it's merged, I would recommend opening a new PR with the changes.

**Comment by Geczy** [comment]
the labels aren't being applied

`ability, ability-draft, cosmetic, item, and tooltip`

perhaps they need to be created before they can be?

**Comment by Geczy** [comment]
dang thats a big miss

**Comment by BeeeQueue** [comment]
No, they would be automatically added by the forms if they we're created in the [label settings](https://github.com/jeffhill/Dota2/labels)

**Comment by Geczy** [comment]
someone create those then

**Comment by BeeeQueue** [comment]
Only repository admins can do that @jeffhill

**Pull request merged**
